include required("shared.conf")

canton {
  mediators {
    mediator1 {
      storage {
        type = postgres
        config {
          dataSourceClass =
            "org.postgresql.ds.PGSimpleDataSource"
          properties {
            serverName = "localhost"
            portNumber = 5432
            databaseName = "mediator1"
            user = "canton"
            password = "canton"
          }
        }
      }

      admin-api {
        address = "0.0.0.0"
        port = 5202
      }
    }
  }
}
