include required("shared.conf")

canton {
  participants {
    participantBuyer {
      storage {
        type = postgres
        config {
          dataSourceClass =
            "org.postgresql.ds.PGSimpleDataSource"
          properties {
            serverName = "localhost"
            portNumber = 5432
            databaseName = "participant_buyer"
            user = "canton"
            password = "canton"
          }
        }
      }

      ledger-api {
        address = "0.0.0.0"
        port = 5021
      }

      admin-api {
        address = "0.0.0.0"
        port = 5022
      }

      http-ledger-api {
        address = "0.0.0.0"
        port = 5023
      }
    }
  }
}
