canton {
  monitoring {
    logging {
      api {
        max-method-length = 1000
        max-message-lines = 10000
      }
    }
  }
  parameters {
    non-standard-config = yes
    timeouts {
      processing {
        verify-active = 40.seconds
      }
    }
  }
}
